# Generated by Django 2.1.3 on 2018-12-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haptest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': '元素管理'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': '模块'},
        ),
        migrations.AlterField(
            model_name='element',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haptest.Plateform'),
        ),
        migrations.AlterModelTable(
            name='element',
            table='haptest_element',
        ),
        migrations.AlterModelTable(
            name='module',
            table='haptest_module',
        ),
    ]
