# Generated by Django 2.1.3 on 2018-12-07 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haptest', '0002_auto_20181206_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='platform',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='haptest.Plateform', verbose_name='所属平台'),
        ),
    ]
