# Generated by Django 2.1.3 on 2018-12-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haptest', '0003_auto_20181207_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': '元素'},
        ),
        migrations.RenameField(
            model_name='element',
            old_name='project',
            new_name='plateform',
        ),
        migrations.AlterField(
            model_name='element',
            name='by',
            field=models.CharField(choices=[('current_url', 'current_url'), ('title', 'title')], max_length=30, verbose_name='by'),
        ),
        migrations.AlterField(
            model_name='element',
            name='custom',
            field=models.CharField(max_length=50, verbose_name='custom'),
        ),
        migrations.AlterField(
            model_name='element',
            name='element',
            field=models.CharField(max_length=30, verbose_name='element'),
        ),
        migrations.AlterField(
            model_name='element',
            name='page',
            field=models.CharField(max_length=20, verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='element',
            name='remark',
            field=models.CharField(max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='element',
            name='value',
            field=models.CharField(max_length=200, verbose_name='value'),
        ),
    ]
