# Generated by Django 2.1.3 on 2018-12-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haptest', '0004_auto_20181207_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='by',
            field=models.CharField(choices=[('class_name', 'class_name'), ('alert', 'alert'), ('title', 'title'), ('id', 'id'), ('xpath', 'xpath'), ('link_text', 'link_text'), ('url', 'url'), ('partial_link_text', 'partial_link_text'), ('current_url', 'current_url')], default='xpath', max_length=30, null=True, verbose_name='by'),
        ),
        migrations.AlterField(
            model_name='element',
            name='custom',
            field=models.CharField(max_length=50, null=True, verbose_name='custom'),
        ),
        migrations.AlterField(
            model_name='element',
            name='plateform',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='haptest.Plateform'),
        ),
        migrations.AlterField(
            model_name='element',
            name='remark',
            field=models.CharField(max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='element',
            name='value',
            field=models.CharField(max_length=200, null=True, verbose_name='value'),
        ),
    ]
