# Generated by Django 2.1.3 on 2018-12-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haptest', '0007_auto_20181214_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': '元素管理'},
        ),
        migrations.AlterField(
            model_name='element',
            name='by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='custom',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='element',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='element',
            name='page',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='element',
            name='plateform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haptest.Plateform'),
        ),
        migrations.AlterField(
            model_name='element',
            name='remark',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='value',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
