# Generated by Django 2.1.3 on 2018-12-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haptest', '0008_auto_20181214_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='by',
            field=models.CharField(max_length=50, verbose_name='by'),
        ),
        migrations.AlterField(
            model_name='element',
            name='custom',
            field=models.CharField(blank=True, max_length=50, verbose_name='custom'),
        ),
        migrations.AlterField(
            model_name='element',
            name='element',
            field=models.CharField(max_length=50, verbose_name='element'),
        ),
        migrations.AlterField(
            model_name='element',
            name='page',
            field=models.CharField(max_length=50, verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='element',
            name='plateform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haptest.Plateform', verbose_name='所属平台'),
        ),
        migrations.AlterField(
            model_name='element',
            name='remark',
            field=models.CharField(blank=True, max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='element',
            name='value',
            field=models.CharField(max_length=50, verbose_name='value'),
        ),
    ]
