# Generated by Django 2.1.3 on 2018-12-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haptest', '0009_auto_20181214_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element',
            field=models.CharField(max_length=50, verbose_name='元素'),
        ),
        migrations.AlterField(
            model_name='element',
            name='page',
            field=models.CharField(max_length=50, verbose_name='页面'),
        ),
        migrations.AlterField(
            model_name='element',
            name='plateform',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='haptest.Plateform', verbose_name='所属平台'),
        ),
    ]
