# Generated by Django 2.1.3 on 2018-12-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haptest', '0010_auto_20181214_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='remark',
            field=models.TextField(blank=True, max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='element',
            name='value',
            field=models.TextField(max_length=300, verbose_name='value'),
        ),
    ]
