# Generated by Django 2.1.3 on 2018-12-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haptest', '0011_auto_20181217_1027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('page', 'element')},
        ),
    ]
