# Generated by Django 2.1.3 on 2018-12-29 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181229_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='dur_data',
            field=models.DurationField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='review_name',
            field=models.CharField(help_text='review_name帮助信息', max_length=30),
        ),
    ]
