# Generated by Django 2.1.3 on 2018-12-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181229_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='dur_data',
            field=models.DurationField(blank=True),
        ),
    ]
