# Generated by Django 2.1.3 on 2018-12-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20181229_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='filePathField_case',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
