# Generated by Django 2.1.3 on 2018-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_bookreview_filepathfield_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='fileField_case',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='filePathField_case',
            field=models.FilePathField(blank=True),
        ),
    ]
