# Generated by Django 2.1.3 on 2018-12-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20181229_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='filePathField_case',
            field=models.FilePathField(blank=True, path='d:/'),
        ),
    ]
