# Generated by Django 2.1.3 on 2018-12-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_bookreview_foreignkey_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='review_name',
            field=models.CharField(blank=True, help_text='review_name帮助信息', max_length=30, null=True),
        ),
    ]
