# Generated by Django 2.1.3 on 2018-12-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haptest', '0002_auto_20181204_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='platform',
            field=models.CharField(default='prod3', max_length=50, verbose_name='平台'),
        ),
    ]
